### ISSUE TITLE
分词TokenAnalysis可以直接在select中使用吗？

### ISSUE THREAD

**Issue by kaixinbuyu** [allwefantasy/streamingpro#609]
现在分词是train out1 as TokenAnalysis.`/tmp/model` where train 保存到parquet文件的方式进行调用的
训练的时候没有问题，写一次文件也无妨。

但是预测阶段，要先分词，输入的每一个预测样本都走保存临时文件这种方式肯定不行。

不知TokenAnalysis可否像TfIdfInPlace那样
直接select TokenAnalysis("我的文本") as xxx不？

**Comment by allwefantasy** [comment]
TokenAnalysis 不支持像 TfIdfInPlace 那样直接对单条做预测。不过其实也是可以做到的。
