### ISSUE TITLE
spark+word2vec如何加载预训练的词向量?

### ISSUE THREAD

**Issue by kaixinbuyu** [allwefantasy/streamingpro#617]
我能找到的spark+word2vec的例子都是将docs作为训练数据,调用word2vecModel.fit()和transform()得到本次训练的词向量.或者load word2vec bin模型的接口。
但我想在spark中加载从其他地方拿到的**预训练的word2vec词向量**, 在model相关类中没有找到相关的接口方法.

**Comment by kaixinbuyu** [comment]
最新的spark代码里有load save了 我试一下最新的代码

**Comment by kaixinbuyu** [comment]
org.apache.spark.mllib.feature.Word2VecModel只有load，save  bin类型的模型的接口。没有load vector的接口。是不是只能在其他地方导出成bin模型再load到spark？

**Comment by allwefantasy** [comment]
You can check the source code of `streaming.dsl.mmlib.algs.SQLWord2VecInPlace`, the Scala file shows you how to get the word -> vector mapping.

Here are some example code:

```scala
 def load(sparkSession: SparkSession, path: String, params: Map[String, String]) = {
    val model = Word2VecModel.load(path)
    model.getVectors.collect().
      map(f => (f.getAs[String]("word"), f.getAs[DenseVector]("vector").toArray)).
      toMap
  }
```

We will close this issue. You can reopen it or create a new one if you have any other quetion.
